### ISSUE TITLE
[BUG] Trash extension

### ISSUE THREAD

**Issue by komi2292** [iamxyntho/seekonscroll#1]
# Describe the bug

Your extension is trash and the feature is useless af. I hate it.

# Steps to Reproduce
# Additional Notes

**Comment by DawarTheDastardly** [comment]
your extension does NOTHING
it serves ZERO purpose

**Comment by DawarTheDastardly** [comment]
also not really i thought it'd be funny cool extension in all seriousness

**Comment by iamxyntho** [comment]
Just uninstall the extension duh, who tf told you to install it in the first place fr 🙄
